---
- name: varible in yaml
  hosts: all
  tasks:
    - debug:
        msg: "www.google.com"

# By using varibles

- name: varible in yaml
  hosts: all
  vars:
    - url : "global.www.google.com"
  tasks:
     debug:
        msg: "{{ url }}"
        vars:
          url: "local.google.com"

- name: varible using again 
  tasks: 
    debug:
      msg: "{{ url }}"

- name: varibles uded global 
  tasks:
    debug:
      msg: "{{ url }}"

- name: print os distribution 
  debug:
    msg: "{{ ansible_distribution }}"
    
- name: print os ipv4
  debug:
    msg:  "{{ ansible_lo.ipv4.address}}"
...

